
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://silvercandy030.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Tang Xiuwen"
title: "{ Tang Xiuwen  }"
description: ""
keywords: ""
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Thanks for reading."
  - text: "Hava a nice day."

me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/dynamic.jpg"
    title: "Dynamic release of campus information based on real-time positioning"
    date: "April 2018"
    description: "An information publishing platform, the information in the platform in the form of landmarks on the map of the publishing location, to help users quickly locate hot events, hot areas."
    level: "University-level general subjects of extracurricular research"
    honor: "Acquired the software copyright"
  - image: "/img/timeline/BCI.jpg"
    title: "Character recognition system based on brain-computer interface technology"
    date: " April 2019"
    description: "A barrier-free human-computer interaction system with a low cost of less than 1000 yuan helps patients with severe motor function disease to convey the information in their mind through eeg, identify the words they want to enter and complete the input function"
    level: "National undergraduate innovation and entrepreneurship program"
    honor: "Related paper “Character Input System Based on Eye Electricity” was accepted by the Chinese core journal “Computer Systems & Applications”" 
  - image: "/img/timeline/hq.jpg"
    title: "Hengqin island tourism industry development research: importance-performance analysis based on online reviews"  
    date: "December 2018 - today"
    description: "The project is to mine useful information from online reviews, automatically analyze the emotional tendencies of a large number of travel reviews through cutting-edge artificial intelligence techniques, calculate and evaluate the performance (satisfaction) and importance (importance) of each attribute, and build an IPA map to study the current status of tourism resources in Hengqin Island. According to the classification and market division of Hengqin Island, we plan for the development of Hengqin Island from seven aspects: food, housing, travel, tourism, purchase, entertainment and sport."
    level: "University-level undergraduate innovation and entrepreneurship projects"
    honor: ""
# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "silvercandy@126.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Awards: 'latest-post'
  Projects: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
